// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4oa5fpvCvGsCoy1zCw9Z9OSqz7Rk6dk4',
    appId: '1:1055348892818:web:2c59d86928746b5e40724b',
    messagingSenderId: '1055348892818',
    projectId: 'creative-307ea',
    authDomain: 'creative-307ea.firebaseapp.com',
    databaseURL: 'https://creative-307ea-default-rtdb.firebaseio.com',
    storageBucket: 'creative-307ea.firebasestorage.app',
    measurementId: 'G-7M7B7LG84S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhEkA-FWM3IyeZC9ueZ0U9aPnbwAvnmo',
    appId: '1:1055348892818:android:fc847fc3e6ae389040724b',
    messagingSenderId: '1055348892818',
    projectId: 'creative-307ea',
    databaseURL: 'https://creative-307ea-default-rtdb.firebaseio.com',
    storageBucket: 'creative-307ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrdD72TH5hrCtMc8t_oWwoPivlkV0mYR4',
    appId: '1:1055348892818:ios:8de7db2279134b7340724b',
    messagingSenderId: '1055348892818',
    projectId: 'creative-307ea',
    databaseURL: 'https://creative-307ea-default-rtdb.firebaseio.com',
    storageBucket: 'creative-307ea.firebasestorage.app',
    iosClientId: '1055348892818-85e3svlmm688qkna6j37gmg49drg8r6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaCompressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrdD72TH5hrCtMc8t_oWwoPivlkV0mYR4',
    appId: '1:1055348892818:ios:8de7db2279134b7340724b',
    messagingSenderId: '1055348892818',
    projectId: 'creative-307ea',
    databaseURL: 'https://creative-307ea-default-rtdb.firebaseio.com',
    storageBucket: 'creative-307ea.firebasestorage.app',
    iosClientId: '1055348892818-85e3svlmm688qkna6j37gmg49drg8r6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaCompressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4oa5fpvCvGsCoy1zCw9Z9OSqz7Rk6dk4',
    appId: '1:1055348892818:web:bc7a38103e9c58ad40724b',
    messagingSenderId: '1055348892818',
    projectId: 'creative-307ea',
    authDomain: 'creative-307ea.firebaseapp.com',
    databaseURL: 'https://creative-307ea-default-rtdb.firebaseio.com',
    storageBucket: 'creative-307ea.firebasestorage.app',
    measurementId: 'G-20D42DL0KB',
  );
}
